### PR TITLE
[Fix] MsgCreateGauge

### PR DESCRIPTION
**Pull request by triccs**
Change pool_id to an Option<u64> so you can create gauges ByDuration

### CODE REVIEW

**Comment by triccs** [comment]
@iboss-ptk is there anyway we could get PR #89 & PR #87 merged & released before Oct. 2nd? I'm looking to get the incentives working for a potential launch at that time.

**Comment by iboss-ptk** [comment]
> @iboss-ptk is there anyway we could get PR https://github.com/osmosis-labs/osmosis-rust/pull/89 & PR https://github.com/osmosis-labs/osmosis-rust/pull/87 merged & released before Oct. 2nd? I'm looking to get the incentives working for a potential launch at that time.

That's possible @triccs. For this PR it looks a bit tricky, fixing generated code directly will be overwritten but to automate this, it seems that it's very specific to this field of this msg but for not all `u64`. 

One way I can think of is to modify [this transformer](https://github.com/osmosis-labs/osmosis-rust/blob/d173d7767ad79246005be189a4113feb7823e203/packages/proto-build/src/transform.rs#L164C16-L164C56) to also take `src: &Path, descriptor: &FileDescriptorSet`, with that we can use [`get_type_url`](https://github.com/osmosis-labs/osmosis-rust/blob/d173d7767ad79246005be189a4113feb7823e203/packages/proto-build/src/transformers.rs#L260) in the transformer and allow us to specify optional int field (hence empty string) like so

[[original]](https://github.com/osmosis-labs/osmosis-rust/blob/d173d7767ad79246005be189a4113feb7823e203/packages/proto-build/src/transform.rs#L164)
```
 transformers::allow_serde_int_as_str(src, s, descriptor, 
   // optional int fields
   vec![
    ("/osmosis.incentives.MsgCreateGauge", vec!["pool_id"])
  ]
)
```

I can work on this if you want, can get it up before Oct 2nd. Gotta clear some other work first this week :)

**Comment by iboss-ptk** [comment]
As I investigated this, I don't think it's worth patching the type like this. I think what would make sense is to mark this field optional in proto file.

In the meantime, you can just set pool_id = 0 ([ref](https://github.com/osmosis-labs/osmosis/blob/1985c871be5a0339923de0b9ff407ef6cc97ba6b/x/incentives/keeper/gauge.go#L168-L171))

**Comment by triccs** [comment]
> As I investigated this, I don't think it's worth patching the type like this. I think what would make sense is to mark this field optional in proto file.
> 
> In the meantime, you can just set pool_id = 0 ([ref](https://github.com/osmosis-labs/osmosis/blob/1985c871be5a0339923de0b9ff407ef6cc97ba6b/x/incentives/keeper/gauge.go#L168-L171))

Thank you, my bad then I could've found this.

**Pull request closed without merging**
