### PR TITLE
Run proto-build over latest version of osmosis

### PR DESCRIPTION
**Pull request by georgemc98**
Hello.  This PR compiles the latest version of Osmosis  @ commit 358eb2cf89ba5e0758a006d24920b98ca0b98808.  We need it specifically for the two new pool queries merged in @ commit 94534da031b67a2eca6c24a98a266451130f41e5.  Thank you for showing me the command to run the proto build @iboss-ptk

### CODE REVIEW

**Comment by iboss-ptk** [comment]
@georgemc98 Thank you! could you help run `cargo clippy --fix` few times til those `Eq` diffs are gone?

**Comment by georgemc98** [comment]
> @georgemc98 Thank you! could you help run `cargo clippy --fix` few times til those `Eq` diffs are gone?

Are there any other commands to run?  I am not getting the same results when I run `cargo clippy --fix`.  The `Eq`diffs remain there

**Comment by iboss-ptk** [comment]
what I normally do is `cargo clippy --fix --allow-dirty` (without `--allow-dirty` you have to always commit). And for some reason I haven't quite figured out, it needs to run few times before all the `Eq` diffs are gone.

**Comment by iboss-ptk** [comment]
#55 should fix the problem, no need for clippy fix anymore

**Comment by georgemc98** [comment]
> #55 should fix the problem, no need for clippy fix anymore

Thanks, this PR should be good to go then.  Quick question, do you know how to Serialize a struct to Proto type Any?  I need to encode a `Pool` struct to an `Any` type in the `QueryPoolResponse`.

**Pull request merged**
